# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.file_api import FileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFileApi(unittest.TestCase):
    """FileApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.file_api.FileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_file_content(self):
        """Test case for get_file_content

        Get file  # noqa: E501
        """
        pass

    def test_get_file_info(self):
        """Test case for get_file_info

        Get file  # noqa: E501
        """
        pass

    def test_get_files_in_folder(self):
        """Test case for get_files_in_folder

        Get files in folder  # noqa: E501
        """
        pass

    def test_put_file_content(self):
        """Test case for put_file_content

        Upload file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
