# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.application_deployment_specification_files import ApplicationDeploymentSpecificationFiles  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicationDeploymentSpecificationFiles(unittest.TestCase):
    """ApplicationDeploymentSpecificationFiles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApplicationDeploymentSpecificationFiles(self):
        """Test ApplicationDeploymentSpecificationFiles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.application_deployment_specification_files.ApplicationDeploymentSpecificationFiles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
