# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sync_api import SyncApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSyncApi(unittest.TestCase):
    """SyncApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sync_api.SyncApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sync_history(self):
        """Test case for get_sync_history

        Get sync history  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
