# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.case_api import CaseApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCaseApi(unittest.TestCase):
    """CaseApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.case_api.CaseApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_or_update_case(self):
        """Test case for add_or_update_case

        Add or update new cases to dictionary  # noqa: E501
        """
        pass

    def test_delete_case(self):
        """Test case for delete_case

        Delete existing case  # noqa: E501
        """
        pass

    def test_get_case_by_id(self):
        """Test case for get_case_by_id

        Get case by id  # noqa: E501
        """
        pass

    def test_get_cases_for_dict(self):
        """Test case for get_cases_for_dict

        Get cases for dictionary  # noqa: E501
        """
        pass

    def test_get_sync_history(self):
        """Test case for get_sync_history

        Get sync history  # noqa: E501
        """
        pass

    def test_update_case(self):
        """Test case for update_case

        Update existing case  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
