# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.app_api import AppApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.app_api.AppApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_app(self):
        """Test case for delete_app

        Delete app  # noqa: E501
        """
        pass

    def test_get_app(self):
        """Test case for get_app

        Get app package  # noqa: E501
        """
        pass

    def test_get_apps(self):
        """Test case for get_apps

        Get list of applications  # noqa: E501
        """
        pass

    def test_update_app(self):
        """Test case for update_app

        Upload app package  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
