# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.clock_vector import ClockVector  # noqa: E501
from swagger_client.rest import ApiException


class TestClockVector(unittest.TestCase):
    """ClockVector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClockVector(self):
        """Test ClockVector"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.clock_vector.ClockVector()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
