# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dictionary_api import DictionaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDictionaryApi(unittest.TestCase):
    """DictionaryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.dictionary_api.DictionaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_dictionary(self):
        """Test case for add_dictionary

        Add new dictionary  # noqa: E501
        """
        pass

    def test_delete_dictionary(self):
        """Test case for delete_dictionary

        Delete dictionary  # noqa: E501
        """
        pass

    def test_get_dict_by_name(self):
        """Test case for get_dict_by_name

        Get dictionary by name  # noqa: E501
        """
        pass

    def test_list_dictionaries(self):
        """Test case for list_dictionaries

        List dictionaries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
