# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.note_list import NoteList  # noqa: E501
from swagger_client.rest import ApiException


class TestNoteList(unittest.TestCase):
    """NoteList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNoteList(self):
        """Test NoteList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.note_list.NoteList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
