# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Dictionary(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'label': 'str',
        'case_count': 'int'
    }

    attribute_map = {
        'name': 'name',
        'label': 'label',
        'case_count': 'caseCount'
    }

    def __init__(self, name=None, label=None, case_count=None):  # noqa: E501
        """Dictionary - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._label = None
        self._case_count = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if label is not None:
            self.label = label
        if case_count is not None:
            self.case_count = case_count

    @property
    def name(self):
        """Gets the name of this Dictionary.  # noqa: E501

        name of dictionary  # noqa: E501

        :return: The name of this Dictionary.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Dictionary.

        name of dictionary  # noqa: E501

        :param name: The name of this Dictionary.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def label(self):
        """Gets the label of this Dictionary.  # noqa: E501

        label of dictionary  # noqa: E501

        :return: The label of this Dictionary.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this Dictionary.

        label of dictionary  # noqa: E501

        :param label: The label of this Dictionary.  # noqa: E501
        :type: str
        """

        self._label = label

    @property
    def case_count(self):
        """Gets the case_count of this Dictionary.  # noqa: E501

        total number of cases in dictionary  # noqa: E501

        :return: The case_count of this Dictionary.  # noqa: E501
        :rtype: int
        """
        return self._case_count

    @case_count.setter
    def case_count(self, case_count):
        """Sets the case_count of this Dictionary.

        total number of cases in dictionary  # noqa: E501

        :param case_count: The case_count of this Dictionary.  # noqa: E501
        :type: int
        """

        self._case_count = case_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Dictionary, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Dictionary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
