# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class FileInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'name': 'str',
        'directory': 'str',
        'md5': 'str',
        'size': 'int'
    }

    attribute_map = {
        'type': 'type',
        'name': 'name',
        'directory': 'directory',
        'md5': 'md5',
        'size': 'size'
    }

    def __init__(self, type=None, name=None, directory=None, md5=None, size=None):  # noqa: E501
        """FileInfo - a model defined in Swagger"""  # noqa: E501

        self._type = None
        self._name = None
        self._directory = None
        self._md5 = None
        self._size = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if name is not None:
            self.name = name
        if directory is not None:
            self.directory = directory
        if md5 is not None:
            self.md5 = md5
        if size is not None:
            self.size = size

    @property
    def type(self):
        """Gets the type of this FileInfo.  # noqa: E501

        either \"file\" or \"directory\"  # noqa: E501

        :return: The type of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this FileInfo.

        either \"file\" or \"directory\"  # noqa: E501

        :param type: The type of this FileInfo.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def name(self):
        """Gets the name of this FileInfo.  # noqa: E501

        name of file or directory without path  # noqa: E501

        :return: The name of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this FileInfo.

        name of file or directory without path  # noqa: E501

        :param name: The name of this FileInfo.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def directory(self):
        """Gets the directory of this FileInfo.  # noqa: E501

        absolute of path directory containing file (for files) or absolute path of parent directory (for directories)  # noqa: E501

        :return: The directory of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._directory

    @directory.setter
    def directory(self, directory):
        """Sets the directory of this FileInfo.

        absolute of path directory containing file (for files) or absolute path of parent directory (for directories)  # noqa: E501

        :param directory: The directory of this FileInfo.  # noqa: E501
        :type: str
        """

        self._directory = directory

    @property
    def md5(self):
        """Gets the md5 of this FileInfo.  # noqa: E501

        md5 signature of file (file only)  # noqa: E501

        :return: The md5 of this FileInfo.  # noqa: E501
        :rtype: str
        """
        return self._md5

    @md5.setter
    def md5(self, md5):
        """Sets the md5 of this FileInfo.

        md5 signature of file (file only)  # noqa: E501

        :param md5: The md5 of this FileInfo.  # noqa: E501
        :type: str
        """

        self._md5 = md5

    @property
    def size(self):
        """Gets the size of this FileInfo.  # noqa: E501

        size of file in bytes (file only)  # noqa: E501

        :return: The size of this FileInfo.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this FileInfo.

        size of file in bytes (file only)  # noqa: E501

        :param size: The size of this FileInfo.  # noqa: E501
        :type: int
        """

        self._size = size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FileInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FileInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
