# coding: utf-8

"""
    CSPro Sync

    Web API for synchronizing data and files from devices in the field to a web server.   # noqa: E501

    OpenAPI spec version: 1.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PartialSaveStatus(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'mode': 'str',
        'field': 'Field'
    }

    attribute_map = {
        'mode': 'mode',
        'field': 'field'
    }

    def __init__(self, mode=None, field=None):  # noqa: E501
        """PartialSaveStatus - a model defined in Swagger"""  # noqa: E501

        self._mode = None
        self._field = None
        self.discriminator = None

        if mode is not None:
            self.mode = mode
        if field is not None:
            self.field = field

    @property
    def mode(self):
        """Gets the mode of this PartialSaveStatus.  # noqa: E501

        \"add\" or \"modify\"  # noqa: E501

        :return: The mode of this PartialSaveStatus.  # noqa: E501
        :rtype: str
        """
        return self._mode

    @mode.setter
    def mode(self, mode):
        """Sets the mode of this PartialSaveStatus.

        \"add\" or \"modify\"  # noqa: E501

        :param mode: The mode of this PartialSaveStatus.  # noqa: E501
        :type: str
        """

        self._mode = mode

    @property
    def field(self):
        """Gets the field of this PartialSaveStatus.  # noqa: E501


        :return: The field of this PartialSaveStatus.  # noqa: E501
        :rtype: Field
        """
        return self._field

    @field.setter
    def field(self, field):
        """Sets the field of this PartialSaveStatus.


        :param field: The field of this PartialSaveStatus.  # noqa: E501
        :type: Field
        """

        self._field = field

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PartialSaveStatus, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PartialSaveStatus):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
